# 个人摄影师微信小程序 - 小程序端配置文件
spring:
  profiles:
    active: dev

# 服务器配置
server:
  port: 8081
  servlet:
    context-path: /miniapp-api

# 应用信息
info:
  app:
    name: 个人摄影师微信小程序-小程序端
    version: 1.0.0
    description: 为摄影师和客户提供作品展示、预约服务的微信小程序后端API

# 日志配置
logging:
  config: classpath:logback-miniapp.xml
